name: upfunda_app
description: "Upfunda Education Platform - Student App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  dio: ^5.4.3
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0
  flutter_html: ^3.0.0-beta.2
  shared_preferences: ^2.2.3
  audioplayers: ^6.0.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  flutter_dotenv: ^5.2.1
  intl_phone_field: ^3.2.0
  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/signup/
    - "assets/images/3. SignUp-Email/"
    - "assets/log in page/"
    - assets/images/home/
    - assets/audio/
    - "assets/7. Academy Path/"
    - "assets/5. Home Page/"
    - "assets/8. Logical Reasoning/"
    - "assets/9. Mental Math/"
    - "assets/10. Olympiad path/"
    - "assets/Quiz Buttons/"
    - "assets/Updated 2/"
    - "assets/academic_math/"
    - "assets/logical_reasoning/"
    - "assets/mental_math/"
    - "assets/continue button/"
    - "assets/images/quick_menu/"
    - "assets/images/quiz/"
    - "assets/audio/"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#6B63D4"
  adaptive_icon_foreground: "assets/images/app_icon.png"
